apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qs51nvmyv-nodejs 
  janus-idp.io/tekton: qs51nvmyv-nodejs
  backstage.io/kubernetes-id: qs51nvmyv-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qs51nvmyv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml