apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qs51nvmyv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qs51nvmyv-nodejs 
  name: qs51nvmyv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qs51nvmyv-nodejs 
